### ISSUE TITLE
Setting c_max considering label length

### ISSUE THREAD

**Issue by bamiikim** [kaist-dmlab/CrossMatch#11]
Thank you for sharing your excellent work!

I have one question: Is it important to consider cases where labels are mixed when determining the hyperparameter c_max? I'm curious about how to set c_max when time series have significantly different label lengths.

I appreciate your response in advance.

**Comment by YoojuShin** [comment]
Very good point. I would chose c_max as short as possible that do not exceed the minimum length of class labels in that case to prevent information flow from different classes.
